services:
  # ðŸ§© Flask API
  flask_app:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: mi-flask-api
    depends_on:
      - mongo_db
    environment:
      # --- URIs de conexiÃ³n ---
      MONGODB_ATLAS_URI: ${MONGODB_ATLAS_URI}
      MONGODB_LOCAL_URI: mongodb://${MONGO_LOCAL_USERNAME}:${MONGO_LOCAL_PASSWORD}@mongo_db:${MONGO_LOCAL_PORT}/${MONGO_LOCAL_DB}?authSource=admin
    ports:
      - "6001:5000"
    networks:
      - mongito-net
    restart: always

  # ðŸ§© MongoDB Local
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOCAL_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_LOCAL_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mongito-net
    restart: always

  # ðŸ§© Mongo Express (para la BD local)
  mongo_express_local:
    image: mongo-express:latest
    container_name: mongo_express_local
    depends_on:
      - mongo_db
    environment:
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    ports:
      - "8085:8081"
    networks:
      - mongito-net
    restart: always

  # ðŸ§© Mongo Express (para Atlas)
  mongo_express_atlas:
    image: mongo-express:latest
    container_name: mongo_express_atlas
    environment:
      ME_CONFIG_MONGODB_URL: ${MONGODB_ATLAS_URI}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    ports:
      - "8082:8081"
    networks:
      - mongito-net
    restart: always

  # ðŸ§© Grafana
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    environment:
      - GF_PLUGINS_PREINSTALL_SYNC=grafana-simple-json-datasource
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - mongito-net
    depends_on:
      - flask_app

# Redes y volÃºmenes
networks:
  mongito-net:

volumes:
  mongo-data:
  grafana-storage:
